language: ruby
cache: bundler
rvm:
- 2.7
sudo: false
deploy:
  edge:
    source: criteo-forks/dpl
    branch: chef_ruby2
  skip_cleanup: true
  provider: chef-supermarket
  user_id: criteo
  cookbook_category: Networking
  client_key: .travis/client.pem
  on:
    tags: true
    all_branches: false
before_deploy:
- openssl aes-256-cbc -K $encrypted_4711d9f1a444_key -iv $encrypted_4711d9f1a444_iv
  -in .travis/client.pem.enc -out .travis/client.pem -d
