name             'winrm-config'
maintainer       'Criteo'
maintainer_email 'b.courtois@criteo.com'
license          'Apache-2.0'
description      'Configures winrm service and client'
version          '0.2.9'
supports         'windows', '>= 6.0'
depends          'windows', '>= 2.1'
chef_version     '>= 13'
issues_url       'https://github.com/criteo-cookbooks/winrm-config/issues'
source_url       'https://github.com/criteo-cookbooks/winrm-config'
