name             'winrm-config-test'
maintainer       'Criteo'
maintainer_email 'b.courtois@criteo.com'
license          'Apache-2.0'
description      'Test cookbook for winrm-config'
version          '0.1.0'
supports         'windows', '>= 6.0'
depends          'winrm-config'
